server:
  port: 9001
spring:
  application:
    name: webServer
  datasource:
    url: jdbc:mysql://localhost:3306/hchat?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: forever

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

logging:
  level:
    com: debug
  config: classpath:log4j2.xml




